### ISSUE TITLE
Failed resolution of: Lio/reactivex/Observable 

### ISSUE THREAD

**Issue by iRYO400** [WindSekirun/NaraeAudioRecorder#6]
Please, make library more modular, remove RxJava and RichUtilsKt

```
Process: com.askme.android.client, PID: 22483
    java.lang.NoClassDefFoundError: Failed resolution of: Lio/reactivex/Observable;
        at com.github.windsekirun.naraeaudiorecorder.NaraeAudioRecorder.startTimer(NaraeAudioRecorder.kt:220)
        at com.github.windsekirun.naraeaudiorecorder.NaraeAudioRecorder.startRecording(NaraeAudioRecorder.kt:100)
```

**Comment by WindSekirun** [comment]
I have plan to remove RichUtilsKt in #7, but removing RxJava takes a bit of trouble.

**Comment by WindSekirun** [comment]
deployed in 1.2.0 (closed)
